### ISSUE TITLE
Guidelines

### ISSUE THREAD

**Issue by pedrofsn** [joselinoneto/JCApp#3]
Devemos focar em todos fazermos um app exatamente igual pra "medir o esforço" em plataformas distintas. Ou podemos adotar soluções mais interessantes relativas a cada plataforma? 

Ex.: No app atual a barar de busca está abaixo da NavigationController/Toolbar/ActionBar. Mas no android, a forma recomendada para este cenário, seria de adicionar o ícone da busca dentro da NavigationController/Toolbar/ActionBar. E ao clicar, ela seria expandida, como citado em https://developer.android.com/guide/topics/search/search-dialog.

**Comment by joselinoneto** [comment]
Acredito que o melhor cada plataforma, o Layout inicial pode ser uma referênica, mas não é uma exigência.

**Comment by pedrofsn** [comment]
Concordo!
